[package]
name = "hs_app"
version = "0.1.0-dirty"
authors = ["CodeSteak <codesteak@shellf.art>"]

[dependencies]
reqwest = "^0.9.0"
select = "^0.4.2"
chrono = "0.4"
unicode-segmentation = "1.1.0"
nix = "0.11.0"
signal = "0.6.0"


[profile.release]
lto = true
