[package]
name = "hs_crawler"
version = "0.2.0"
authors = ["robin <robin@shellf.art>"]
edition = "2018"

[dependencies]
select = "^0.4.2"
reqwest = {version="0.11", features = ["blocking", "json"]}
chrono = "0.4"
