[package]
name = "hs_crawler"
version = "0.3.0"
authors = ["robin <robin@shellf.art>"]
edition = "2018"

[dependencies]
select = "0.5"
reqwest = {version="0.11", features = ["blocking", "json"]}
chrono = "0.4"
